# URL: /home/laboratorio/TFM/agarre_ros2_ws/src/ur5_tools/setup.cfg
# Summary: Setuptools script install locations for ur5_tools.
[develop]
script_dir=$base/lib/ur5_tools
[install]
install_scripts=$base/lib/ur5_tools

[options.entry_points]
console_scripts =
    camera_capture = ur5_tools.camera_capture:main
    fake_cameras = ur5_tools.fake_cameras:main

[flake8]
max-line-length = 120
extend-ignore = E203, W503

[pydocstyle]
add-ignore = D102, D107
