# URL: /home/laboratorio/TFM/agarre_ros2_ws/src/ur5_qt_panel/setup.cfg
# Summary: Setuptools script install locations for ur5_qt_panel.
[develop]
script_dir = $base/lib/ur5_qt_panel
[install]
install_scripts = $base/lib/ur5_qt_panel

[options.entry_points]
console_scripts =
    ur5_qt_panel = ur5_qt_panel.main_panel:main

[flake8]
max-line-length = 120
ignore = C, D, E, F, I, Q, W

[pydocstyle]
add-ignore = D102, D107
