#!/usr/bin/env bash
# URL: /home/laboratorio/TFM/agarre_ros2_ws/scripts/run_gz_ros_bridge.sh
# Summary: Runs ros_gz_bridge parameter_bridge for cameras and clock.
set -Eeuo pipefail

WS_DIR="${WS_DIR:-$HOME/TFM/agarre_ros2_ws}"
LOG_DIR="$WS_DIR/log"
BASE_YAML="${BASE_YAML:-$WS_DIR/scripts/bridge_cameras.yaml}"
WORLD_FILE="${WORLD_FILE:-$WS_DIR/worlds/ur5_mesa_objetos.sdf}"

if [[ ! -f "$BASE_YAML" ]]; then
  echo "[ERROR] No existe BASE_YAML: $BASE_YAML" >&2
  exit 1
fi

if [[ ! -f "$WORLD_FILE" ]]; then
  echo "[ERROR] No existe WORLD_FILE: $WORLD_FILE" >&2
  exit 1
fi

mkdir -p "$LOG_DIR"

WORLD_NAME="$(sed -n 's/.*<world name="\([^"]*\)".*/\1/p' "$WORLD_FILE" | head -n1)"
WORLD_NAME="${WORLD_NAME:-default}"

RUNTIME_YAML="$LOG_DIR/bridge_runtime.yaml"
cat > "$RUNTIME_YAML" <<EOF2
# AUTO-GENERATED by run_gz_ros_bridge.sh
# world_name = $WORLD_NAME

- ros_topic_name: /clock
  gz_topic_name: /world/$WORLD_NAME/clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
EOF2

cat "$BASE_YAML" >> "$RUNTIME_YAML"

echo "[INFO] Cargando entorno ROS 2 Jazzy..."
set +u
export AMENT_TRACE_SETUP_FILES="${AMENT_TRACE_SETUP_FILES:-}"
source /opt/ros/jazzy/setup.bash
if [[ -f "$WS_DIR/install/setup.bash" ]]; then
  source "$WS_DIR/install/setup.bash"
fi
set -u

echo "[INFO] Lanzando ros_gz_bridge con config: $RUNTIME_YAML"
ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:="$RUNTIME_YAML"
