#!/usr/bin/env bash
# URL: /home/laboratorio/TFM/agarre_ros2_ws/scripts/ur5_set_table_pose.sh
# Summary: Captures current joint_states and stores them as TABLE positions.
set -Eeuo pipefail

WS_DIR="${WS_DIR:-$HOME/TFM/agarre_ros2_ws}"
TABLE_ENV="${TABLE_ENV:-$WS_DIR/scripts/ur5_table_pose.env}"
CAPTURE_TIMEOUT="${CAPTURE_TIMEOUT:-5}"

# Source entorno (robusto)
set +u
export AMENT_TRACE_SETUP_FILES="${AMENT_TRACE_SETUP_FILES:-}"
export RMW_FASTRTPS_USE_SHM=0
export FASTRTPS_DEFAULT_PROFILES_FILE="${FASTRTPS_DEFAULT_PROFILES_FILE:-$WS_DIR/scripts/fastdds_no_shm.xml}"
source /opt/ros/jazzy/setup.bash
[[ -f "$WS_DIR/install/setup.bash" ]] && source "$WS_DIR/install/setup.bash"
set -u

tmp_out="$(mktemp)"
if ! timeout "$CAPTURE_TIMEOUT" ros2 topic echo --once /joint_states >"$tmp_out" 2>/dev/null; then
  rm -f "$tmp_out"
  echo "[ROBOT] ERROR: No pude leer /joint_states (timeout ${CAPTURE_TIMEOUT}s)." >&2
  exit 1
fi

python3 - "$tmp_out" "$TABLE_ENV" <<'PY'
import re
import sys
from datetime import datetime

in_path = sys.argv[1]
out_path = sys.argv[2]

names = []
positions = []
section = None

for raw in open(in_path, "r", encoding="utf-8", errors="ignore"):
    line = raw.strip()
    if line == "name:":
        section = "name"
        continue
    if line == "position:":
        section = "position"
        continue
    if re.match(r"^[A-Za-z_]+:", line):
        section = None
        continue
    if line.startswith("- "):
        val = line[2:].strip()
        if section == "name":
            names.append(val)
        elif section == "position":
            positions.append(val)

if not names or not positions:
    raise SystemExit("[ROBOT] ERROR: joint_states incompleto (name/position vacios).")

mapping = dict(zip(names, positions))
order = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]

missing = [j for j in order if j not in mapping]
if missing:
    raise SystemExit(f"[ROBOT] ERROR: Faltan joints en /joint_states: {', '.join(missing)}")

vals = [float(mapping[j]) for j in order]
if all(abs(v) < 1e-3 for v in vals):
    raise SystemExit("[ROBOT] ERROR: joint_states es todo 0. No guardo MESA.")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("# AUTO-GENERATED by ur5_set_table_pose.sh\n")
    f.write(f"# {datetime.now().isoformat(timespec='seconds')}\n")
    for i, joint in enumerate(order):
        f.write(f"TABLE_POS_{i}={mapping[joint]}\n")

print(f"[ROBOT] MESA guardada en {out_path}")
PY

rm -f "$tmp_out"
